version: '3.8'

services:
  web:
    build: .
    ports:
      - "5017:5000"
    volumes:
      - .:/app
      - ./docs-gg:/docs
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python /app/app.py
